name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    env:
      CI: true

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          HSE_USERNAME: ${{ secrets.HSE_USERNAME }}
          HSE_PASSWORD: ${{ secrets.HSE_PASSWORD }}
          ADMIN_SCM_USERNAME: ${{ secrets.ADMIN_SCM_USERNAME }}
          ADMIN_SCM_PASSWORD: ${{ secrets.ADMIN_SCM_PASSWORD }}
          VML_USERNAME: ${{ secrets.VML_USERNAME }}
          VML_PASSWORD: ${{ secrets.VML_PASSWORD }}
          HEAD_SCM_USERNAME: ${{ secrets.HEAD_SCM_USERNAME }}
          HEAD_SCM_PASSWORD: ${{ secrets.HEAD_SCM_PASSWORD }}
          CREATOR_PROCPLAN_USERNAME: ${{ secrets.CREATOR_PROCPLAN_USERNAME }}
          CREATOR_PROCPLAN_PASSWORD: ${{ secrets.CREATOR_PROCPLAN_PASSWORD }}
          REQUESTER_PROCPLAN_USERNAME: ${{ secrets.REQUESTER_PROCPLAN_USERNAME }}
          REQUESTER_PROCPLAN_PASSWORD: ${{ secrets.REQUESTER_PROCPLAN_PASSWORD }}
          CONFIRMER_PROCPLAN_USERNAME: ${{ secrets.CONFIRMER_PROCPLAN_USERNAME }}
          CONFIRMER_PROCPLAN_PASSWORD: ${{ secrets.CONFIRMER_PROCPLAN_PASSWORD }}
          REVIEWER_PROCPLAN_USERNAME: ${{ secrets.REVIEWER_PROCPLAN_USERNAME }}
          REVIEWER_PROCPLAN_PASSWORD: ${{ secrets.REVIEWER_PROCPLAN_PASSWORD }}

      - uses: actions/upload-artifact@v6
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
